version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
      
  gateway:
    image: gateway
    build: v2/gateway
    ports:
      - "8080:8080"
      
  loyalty:
    image: loyalty
    build: v2/loyalty
    ports:
      - "8050:8050"
      
  payment:
    image: payment
    build: v2/payment
    ports:
      - "8060:8060"
      
  reservation:
    image: reservation
    build: v2/reservation
    ports:
      - "8070:8070"

volumes:
  db-data: